spring.application.name=com.edu.auth
server.port=8081

spring.security.oauth2.client.registration.google.client-id= 655943232797-ht0e1icdadkm9vcamnabprn5mt8mcnbi.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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